name: PHP

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup PHP environment
      uses: nanasess/setup-php@v3.0.4

    - name: Run test suite
      run: php dsuSign.php
      env:
        user: ${{ secrets.USER }}
        pwd: ${{ secrets.PWD }}
        baseUrl: ${{ secrets.BASEURL }}
        key: ${{ secrets.KEY }}
